# Generated by Django 4.1.5 on 2023-01-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("women", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="womenmodel",
            name="img",
            field=models.ImageField(default=None, upload_to="static/media/"),
        ),
    ]
