# Generated by Django 4.1.5 on 2023-01-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signup", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="signup_model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
                ("contact", models.CharField(max_length=10)),
                ("email", models.EmailField(max_length=50)),
                ("dob", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("", ""),
                            ("Male", "male"),
                            ("Female", "female"),
                            ("Others", "others"),
                        ],
                        default="",
                        max_length=7,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="signup_form_model",
        ),
    ]
