# Generated by Django 4.1.4 on 2023-01-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signup", "0005_signup_model_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signup_model",
            name="gender",
            field=models.CharField(
                choices=[("Male", "male"), ("Female", "female"), ("Others", "others")],
                default="Male",
                max_length=7,
            ),
        ),
    ]
