# Generated by Django 4.1.4 on 2023-01-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signup", "0006_alter_signup_model_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="signupmodel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
                ("dob", models.DateField(default=None)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "male"),
                            ("Female", "female"),
                            ("Others", "others"),
                        ],
                        default="Male",
                        max_length=7,
                    ),
                ),
                ("email", models.EmailField(max_length=50, unique=True)),
                ("contact", models.CharField(max_length=10, unique=True)),
                ("password", models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name="signup_model",
        ),
    ]
