# Generated by Django 4.1.4 on 2023-01-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signup", "0007_signupmodel_delete_signup_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signupmodel",
            name="password",
            field=models.CharField(max_length=100),
        ),
    ]
