# Generated by Django 4.1.5 on 2023-02-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="zomatoapitable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hotel_name", models.CharField(max_length=20)),
                ("area", models.CharField(max_length=15)),
                ("number", models.BigIntegerField()),
                ("special_menu", models.CharField(max_length=20)),
            ],
        ),
    ]
